name: Go
on:
  release:
    types: [ published ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v2
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - 
      name: Set up Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        driver-opts: network=host
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Build and push docker image
      id: docker_build
      uses: docker/build-push-action@v2.4.0
      with:
        push: true
        tags: |
          orcunuso/ocinfo:v1.0.0
          orcunuso/ocinfo:latest
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

# https://github.com/docker/build-push-action
